### ISSUE TITLE
Any planning to Update?

### ISSUE THREAD

**Issue by a-patel** [jqwidgets/ASP.NET-Core-MVC-Bootstrap-Tag-Helpers#2]

**Comment by jqwidgets** [comment]
What kind of update do you expect?

**Comment by a-patel** [comment]
more bootstrap elements' tag helpers?
(e.g. form, label, label with validation, input group, date picker, color picker)
or any optimization and code re-usability by different types of tag helpers

**Comment by jqwidgets** [comment]
Input group and Label are already available. Date Picker, Validation, Color Picker are not Bootstrap elements and as such will not be included.

**Comment by a-patel** [comment]
thank you for help.
